version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          keys:
            - deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
            sudo apt-get install ffmpeg libav-tools
            sudo pip install pipenv
            pipenv install
            mkdir test-reports
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Pyre Type checking
          command: |
            pipenv run pyre --source-directory "vision"
            pipenv run pyre --source-directory "landmarks"
      - run:
          name: Python Unit tests
          command: pipenv run py.test --junit-xml=test-reports/pytest.xml
      - run:
          name: Python Behavioural tests
          command: pipenv run behave --junit --junit-directory test-reports/
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
